version: '3.3'
services:
    db:
      image: mysql
      ports:
        - "3306:3306"
      security_opt:
        - seccomp:unconfined
      volumes:
        - ./docker/data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password